### ISSUE TITLE
[bundle] debian list

### ISSUE THREAD

**Issue by the-maux** [david-barbion/netdiag#10]
Installing pkg-config 1.1.7
Installing ffi 1.9.17 with native extensions
Installing json 2.0.1 with native extensions
Installing net-ping 2.0.1
Using bundler 1.11.2
Installing glib2 3.1.1 with native extensions
Installing cairo 1.15.5 with native extensions
Installing libnotify 0.9.3
Installing atk 3.1.1 with native extensions
Installing gobject-introspection 3.1.1 with native extensions
Installing cairo-gobject 3.1.1 with native extensions
Installing pango 3.1.1 with native extensions
Installing gio2 3.1.1 with native extensions
Installing gdk_pixbuf2 3.1.1
Installing gdk3 3.1.1
Installing gtk2 3.1.1 with native extensions
Installing gtk3 3.1.1 with native extensions
Installing ruby-libappindicator 0.1.5 with native extensions
Installing webkit2-gtk 3.1.1
Bundle complete! 5 Gemfile dependencies, 19 gems now installed.

**Comment by the-maux** [comment]
Error on debian 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64


GLib-GObject-WARNING **: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2461: signal 'child-added' is invalid for instance '0x41fe500' of type 'GtkMenu'
	from ./netindic.rb:73:in `initialize'
	from ./netindic.rb:256:in `new'
	from ./netindic.rb:256:in `<main>'
error 5
/var/lib/gems/2.1.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:296: [BUG] Segmentation fault at 0x00000000000078
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0012 p:---- s:0043 e:000042 CFUNC  :invoke
c:0011 p:0040 s:0038 e:000037 LAMBDA /var/lib/gems/2.1.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:296 [FINISH]
c:0010 p:0032 s:0034 e:000033 LAMBDA /var/lib/gems/2.1.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:307 [FINISH]
c:0009 p:---- s:0029 e:000028 CFUNC  :new
c:0008 p:0083 s:0025 e:000024 METHOD /home/renaud/Tool/netdiag/netdiag/portal.rb:15 [FINISH]
c:0007 p:---- s:0021 e:000020 CFUNC  :new
c:0006 p:0038 s:0017 e:000016 METHOD /home/renaud/Tool/netdiag/netdiag/portal.rb:76
c:0005 p:0114 s:0013 e:000012 METHOD ./netindic.rb:241
c:0004 p:0015 s:0010 e:000009 BLOCK  ./netindic.rb:99 [FINISH]
c:0003 p:---- s:0007 e:000006 CFUNC  :loop
c:0002 p:0007 s:0004 e:000003 BLOCK  ./netindic.rb:96 [FINISH]
c:0001 p:---- s:0002 e:000001 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
./netindic.rb:96:in `block in run'
./netindic.rb:96:in `loop'
./netindic.rb:99:in `block (2 levels) in run'
./netindic.rb:241:in `run_tests'
/home/renaud/Tool/netdiag/netdiag/portal.rb:76:in `open_portal_authenticator_window'
/home/renaud/Tool/netdiag/netdiag/portal.rb:76:in `new'
/home/renaud/Tool/netdiag/netdiag/portal.rb:15:in `initialize'
/home/renaud/Tool/netdiag/netdiag/portal.rb:15:in `new'
/var/lib/gems/2.1.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:307:in `block in load_constructor_infos'
/var/lib/gems/2.1.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:296:in `block (2 levels) in load_constructor_infos'
/var/lib/gems/2.1.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:296:in `invoke'

**Comment by david-barbion** [comment]
Can you check that you have this version of libwebkit2gtk (https://packages.debian.org/fr/jessie/libwebkit2gtk-4.0-37)?

**Comment by david-barbion** [comment]
No activity, closing.
