### ISSUE TITLE
Latest version requires gtk 3.20

### ISSUE THREAD

**Issue by valvin1** [david-barbion/netdiag#11]
When launching netdiag it crashes with this message : 

```
var/lib/gems/2.3.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:530:in `invoke': /home/user/netdiag/netdiag/../preferences.ui:5:1 Required gtk+ version 3.20, current version is 3.18 (Gtk::BuilderError::VersionMismatch)
	from /var/lib/gems/2.3.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:530:in `block in define_method'
	from /home/user/netdiag/netdiag/preferences.rb:7:in `initialize'
	from /home/user/netdiag/netindic.rb:47:in `new'
	from /home/user/netdiag/netindic.rb:47:in `initialize'
	from /home/user/netdiag/netindic.rb:270:in `new'
	from /home/user/netdiag/netindic.rb:270:in `<main>'
```

gtk 3.20 is not present for ubuntu 16.04

**Comment by valvin1** [comment]
thank you :) it works
